name: inkistry
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animator: ^3.1.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
#  sizer: ^2.0.15
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  cached_network_image: ^3.2.0
  uuid: ^3.0.6
  timeago: ^3.2.2
  intl: ^0.17.0
  flutter_native_splash: ^2.0.5
  package_info: ^2.0.2
  buttons_tabbar: ^1.3.4
  readmore: ^2.1.0
  shimmer: ^2.0.0
  giphy_get: ^3.0.5
  auto_direction: ^0.0.5

  # Firebase
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  cloud_functions: ^3.2.14
  firebase_dynamic_links: ^4.2.2
#  paginate_firestore: ^1.0.3
#  firestore_ui: ^1.23.0
  paginate_firestore:
    git:
      url: https://github.com/Masleap-INC/staggered_paginate_firestore.git
      ref: main

  # Social Auth
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1

  # GeoCoding
  geolocator: ^8.2.0
  geocode: ^1.0.1

  # Storage
  path_provider: ^2.0.9
  image_picker: ^0.8.4+10
  flutter_image_compress: ^1.1.0

  # Camera
  camera: ^0.9.4+16
  image_cropper: ^1.5.0

  # Network
  http: ^0.13.4
  dio: ^4.0.6
  image_gallery_saver: ^1.7.1

  # Utilities
  share_plus: ^4.0.4

  #refectoring
  connectivity: ^3.0.6
  flutter_screenutil: ^5.0.0+2
  flex_color_scheme: ^5.1.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.6
  badges: ^2.0.3
  dio_http_cache: ^0.3.0
  percent_indicator: ^4.2.0
  rich_text_controller: ^1.4.0
  video_thumbnail: ^0.5.0
  gallery_saver: ^2.3.2
  pinch_zoom: ^1.0.0

  # staggered_paginate_firestore_package
  flutter_staggered_grid_view: ^0.6.1

  # camera
  video_player: ^2.1.4
  another_xlider: ^1.1.0
  flutter_phoenix: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter packages pub run build_runner build
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular.ttf
        - asset: assets/fonts/Sofia-Pro-Medium.ttf
        - asset: assets/fonts/Sofia-Pro-Semi-Bold.ttf
        - asset: assets/fonts/Sofia-Pro-Bold.ttf

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#FFFFFF"
  image: assets/images/ic_launcher.png
  color_dark: "#212230"
  image_dark: assets/images/ic_launcher.png
  android_gravity: center
  fullscreen: true
